### ISSUE TITLE
No Limit in amount of Characters for Category and Article names

### ISSUE THREAD

**Issue by Hazmes** [scherddel/KiosCash#37]
There is no limit on how many characters the Category and Article name can contain. 
This leads to unpleasent presentation in the Add-Category View and the Add-Article View as described in the picture below.

![kioscash_category_lorem_ipsum](https://cloud.githubusercontent.com/assets/26164958/24556299/2f2d7bea-1634-11e7-9b3a-eb7b4f764223.png)

**Comment by OlliMartin** [comment]
done
