### ISSUE TITLE
Unhandled Exception - Input Check at ChangeStock_StockAmount field necessary

### ISSUE THREAD

**Issue by Hazmes** [scherddel/KiosCash#38]
The "Amount" (On Stock) field in the Change Stock View is not validated. It is possible to copy text in the field which leads to an Unhandled System.InvalidOperationException. 
[KiosCash_ArticleAmount_UnhandledException_Details.txt](https://github.com/scherddel/KiosCash/files/886077/KiosCash_ArticleAmount_UnhandledException_Details.txt)

![image](https://cloud.githubusercontent.com/assets/26164958/24556888/265b6796-1636-11e7-9c88-2b0d2d123398.png)

**Comment by OlliMartin** [comment]
fixed
