### ISSUE TITLE
Overflow Exception - Possibility to sell more items than there are in Stock

### ISSUE THREAD

**Issue by Hazmes** [scherddel/KiosCash#39]
Since this Issue requires a certain amount of steps (very unlikely to happen without forcing), the steps which lead to the Issue are represented in an MHTML Document. 
Basically, when you enter X amounts of a product to an order, then change the stock amount of that exact product to <X and finish the order. The new stock amount will be an overflow value and will cause an Overflow Exception when the project is rebuild. 

[Overflow_Exception_Details.txt](https://github.com/scherddel/KiosCash/files/886369/Overflow_Details.txt)
[Reproducing_Steps.zip](https://github.com/scherddel/KiosCash/files/886371/2.zip)

**Comment by OlliMartin** [comment]
fixed
